config/routes.rb
Rails.application.routes.draw do
  Healthcheck.routes(self)
  get "products/report", to: "products#download_pdf", as: "products_download"

  resources :products

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :product

  validates :kind, presence: true, length: { maximum: 100 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/product.rb
class Product < ApplicationRecord
  extend FriendlyId

  belongs_to :seller
  has_many :inventories, dependent: :destroy

  friendly_id :name, use: :slugged

  accepts_nested_attributes_for :inventories, reject_if: :all_blank, allow_destroy: true
  validates_associated :inventories

  validates :name, presence: true, length: { maximum: 100 }
  validates :description, presence: true, length: { maximum: 500 }
end

app/models/seller.rb
class Seller < ApplicationRecord
    has_many :products

    validates :name, presence: true, length: { maximum: 100 } 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @pagy, @products = pagy(Product.all)
    # @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
    @product = Product.friendly.find(params[:id])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def download_pdf 

    most_in_stock = Product.all.map { |p| [p.name, p.inventories.sum(:quantity)]}.sort_by { |p| -p[1] }.first(10)
    out_of_stock = Inventory.where(quantity: 0)

    pdf = WickedPdf.new.pdf_from_string(            
      render_to_string(partial: 'report', layout: false, locals: { most_in_stock: most_in_stock, out_of_stock: out_of_stock}))  
    send_data(pdf,                                  
      filename: "inventory-report-#{Time.now.strftime("%Y-%d-%m_%H-%M-%S")}.pdf",                    
      type: 'application/pdf',                      
      disposition: 'attachment')                    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.friendly.find(params[:id])
      # redirect_to request.params.merge(id: @product.friendly_id), status: 301 unless @product.friendly_id == params[:id]
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:id, :description, :seller_id, :name, inventories_attributes: [:id, :quantity, :kind, :price, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Logistify</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label "Seller" %>
    <%= form.select :seller_id, Seller.all.each.map { |s| [s.name, s.id ] }, selected: product&.seller&.id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <%= link_to_add_nested(form, :inventories, '#inventory-items', tag: "button") %>

  <div id='inventory-items'>
    <%= form.fields_for :inventories do |inventory_f| %>
      <%= render 'inventory_fields', form: inventory_f %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_inventory.html.erb
<div>
  <p>
    <strong>Type:</strong>
    <%= inv.kind %>
  </p>
  <p>
    <strong>Price:</strong>
    <%= inv.price %>
  </p>
  <p>
    <strong>Quantity:</strong>
    <%= inv.quantity %>
  </p>
</div>

app/views/products/_inventory_fields.html.erb
<div class="wrapper-div">
<%= form.label :kind %>
  <%= form.text_field :kind %>

  <%= form.label :price %>
  <%= form.number_field :price %>
  <%= form.label :quantity %>
  <%= form.number_field :quantity %>


  <%= link_to_remove_nested(form) %> <!-- adds a link to add more items -->
</div>

app/views/products/_report.html.erb
<h1>Most in stock products</h1>
<div>
  <% most_in_stock.each do |arr| %>
    <p><%= arr[0] %>: <%= arr[1] %>
    </p>
  <% end %>
</div>
<h1>Out of stock products</h1>
<div>
  <% out_of_stock.each do |p| %>
    <p><%= p.product.name %> - <%= p.kind %></p>
  <% end %>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<%= link_to 'New Product', new_product_path %>

<%= link_to "Download report", products_download_path %>

<br />

  <%== pagy_nav(@pagy) %>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Seller</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.description %></td>
        <td><%= product.seller.name %></td>
        <td><%= product.name %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>
<p>
  <strong>Seller:</strong>
  <%= @product.seller.name %>
</p>
<p>
  <strong>Product Name:</strong>
  <%= @product.name %>
</p>
<p><strong><u>Types / inventory </u></strong></p>
<div>
  <% @product.inventories.each do |inv| %>
    <%= render "inventory", inv: inv %>
  <% end %>
</div>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>